#Configurar puerto
server:
    port: 8095
    servlet:
        context-path: /msmaestriac


# Configuración de la base de datos
spring:
  datasource:
    url: jdbc:mysql://docker.unicauca.edu.co:3307/computacion
    username: computacion
    password: DB-C0mput4c10N
    #url: jdbc:mysql://localhost:3306/maestriacomputacion
    #username: root
    #password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic

gestion-estudiantes-docentes:
  url: http://localhost:8091/api/
  resources:
    docentes-activos: docentes/listar/{estado}
    obtener-estudiante: estudiantes/informacion-personal/{correo}
    obtener-docente: docentes/obtener-docente/{identificador}
    obtener-estudiante-por-id: estudiantes/informacion-personal-estudiante/{idEstudiante}

gestion-asignaturas:
  url: http://localhost:8021/api/
  resources:
    crear-asignaturas-externas: asignaturasExternas
    obtener-asignatura: asignaturasExternas/obtener-asignatura/{idAsignatura}
    docentes-asignaturas: asignaturas/docentes-asignaturas
